# 6주차 함수&Numpy

## 함수

In [6]:
def print_address():
    print("경기도 성남시 분당구")
    print("금곡동 미금로215")
    print("정해준")

In [7]:
print_address()

경기도 성남시 분당구
금곡동 미금로215
정해준


In [13]:
def caculate_area(r):
    area = 3.14 * r ** 2
    return area
    
c_area = caculate_area(5.0)

In [14]:
c_area

78.5

In [15]:
print(caculate_area)

<function caculate_area at 0x7ff2acb3bea0>


In [16]:
def get_sum(start, end):
    sum=0
    for i in range(start, end+1):
        sum +=1
    return
print (get_sum)



<function get_sum at 0x7ff2acb3ba60>


In [17]:
r = float(input("원의 반지름을 입력해주세요: "))
area=calculate_area(r)
print(area)




원의 반지름을 입력해주세요: 5
78.5


In [21]:
def greet(name, msg="별일 없죠?"):
    print("안녕", name + ","+ msg)
greet("영희", "생일 축하해")



안녕 영희,생일 축하해


In [23]:
def calc(x,y,z):
    return x+y+z
    
    

In [27]:
calc(y=30, z=20, x=10)

60

In [28]:
import numpy

## numpy

In [32]:
# numpy 라이브러리  소환

import numpy as np #np라는 약어로 numpy를 사용


In [34]:
a=np.array([1,2,3])

In [35]:
a

array([1, 2, 3])

In [36]:
a.dtype

dtype('int64')

In [39]:
b=np.array([1,2,3,4.567])

In [40]:
b.dtype

dtype('float64')

In [45]:
c = np.array([1,2,325], dtype=np.float32)

In [46]:
c.dtype

dtype('float32')

## 배열 생성

In [48]:
np.array([1,2,3,4])
# 리스트를 배열화 함

array([1, 2, 3, 4])

In [49]:
np.arange(10)
# arange()를 통해 범위의 값을 배열화함.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.linspace(0,1,5)
#linspace()를 통해 요소의 수를 배열화

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [51]:
#0으로 채운 배열 만들기
np.zeros((2,2))


array([[ 0.,  0.],
       [ 0.,  0.]])

In [52]:
#1로 채운 배열 만들기
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [54]:
#지정된 공간 크기의 비어있는 배열 만들기
np.empty((2,4))

array([[  6.95053715e-310,   2.15023614e-316,   6.95050972e-310,
          6.95050972e-310],
       [  6.95050972e-310,   6.95050972e-310,  -1.60351014e-034,
          1.63041663e-322]])

In [57]:
#다차원 배열 만들기
data=[[1,2,3,4],[5,6,7,8]]
arr=np.array(data)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
x1=np.random.randint(10,size=6)
x1

array([8, 9, 2, 0, 2, 7])

In [78]:
x1[0]


8

In [80]:
x1[-1]
#역으로 꺼내기

7

In [81]:
x2=np.random.randint(10,size=(3,4))

x2

array([[7, 3, 0, 4],
       [9, 7, 4, 3],
       [8, 9, 5, 1]])

In [82]:
x2[0,0]

7

### 배열 슬라이싱

In [83]:
x3=np.arange(10)
x3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
x3[0:5]
#첫 다섯개 요소


array([0, 1, 2, 3, 4])

In [89]:
x3[5:]
#인텍스 5다음 요소들

array([5, 6, 7, 8, 9])

In [90]:
#중간 하위 배열
x3[4:7]

array([4, 5, 6])

### step의 음수 사용

In [91]:
#모든 요소를 거꾸로 나열
x3[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [97]:
#인텍스 5부터 하나 걸러 하나씩 요소를 거꾸로 나열
x3[5::-2]

array([5, 3, 1])

### 다차원 하위 배열

In [103]:
x2
#두 개의 행, 세 개의 열
x2[:2,:3]

array([[7, 3, 0],
       [9, 7, 4]])

In [104]:
#모든 행, 한 열 걸러 하나씩
x2[:,::2]

array([[7, 0],
       [9, 4],
       [8, 5]])

## 배열 확인 및 분할
### 단일 콜론으로 표시된 빈 슬라이스 사용

In [108]:
grid=np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

##  UFuncs(Universal Functions)

#### 백터화 연산이라고 하며, 간단한 배열에 연산을 수행해 각 요소에 적용하므로써 수행

In [110]:
arr = np.ones((3,4))
arr



array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [111]:
arr+1

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [112]:
arr*5

array([[ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.]])

In [117]:
arr*5**2

array([[ 25.,  25.,  25.,  25.],
       [ 25.,  25.,  25.,  25.],
       [ 25.,  25.,  25.,  25.]])

In [119]:
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [121]:
x=np.arange(1,6)
x
#모든 요소의 합을 반환함
np.add.reduce(x)



15

ImportError: No module named 'pandas'

In [126]:
import pandas as pd

ImportError: No module named 'pandas'